services:
  web:
    build:
      context: .
      dockerfile: .Dockerfile
    environment:
      PORT: 8080
      PG_CONNECTION_STRING: postgres://admin:pass@postgres:5432/demo?ssl_disable=false
    ports:
      - 8080:8080
    networks:
      localhost:
        aliases:
          - web
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d demo"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/01-setup.sql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: demo
    networks:
      localhost:
        aliases:
          - postgres
  newman:
    image: postman/newman
    volumes:
      - ./newman:/newman
    command:
      ["run", "/newman/newman-test.postman_collection.json", "-e", "/newman/newman-test.postman_environment.json", "-k"]
    networks:
      localhost:
    depends_on:
      web:
        condition: service_started
networks:
  localhost:
