services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d demo"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./pg-setup.sql:/docker-entrypoint-initdb.d/00-setup.sql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: demo
    networks:
      localhost:
        aliases:
          - postgres
  mongo:
    image: mongo
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      localhost:
        aliases:
          - mongo
    volumes:
      - ./mongo-setup.js:/docker-entrypoint-initdb.d/00-mongo-setup.js
    environment:
      MONGO_INITDB_DATABASE: demo
networks:
  localhost:
