services:
  web:
    build:
      context: .
      dockerfile: .Dockerfile
    environment:
      - PORT=8080
    ports:
      - 8080:8080
    networks:
      localhost:
        aliases:
          - web
  newman:
    image: postman/newman
    volumes:
      - ./newman:/newman
    command:
      ["run", "/newman/newman-test.postman_collection.json", "-e", "/newman/newman-test.postman_environment.json", "-k"]
    networks:
      localhost:
        aliases:
          - web
networks:
  localhost:
